name: WegnerDesign
description: "Nerdy Ramblings, Usually about Javascript"
url: http://www.wegnerdesign.com/blog
safe: true
lsi: false
pygments: true
paginate: 10
auto: true
markdown: redcarpet
permalink: /blog/:title
